//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNtelrcom
{
    using System;
    using System.Collections.Generic;
    
    public partial class CgPCdPh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CgPCdPh()
        {
            this.ATC = new HashSet<ATC>();
        }
    
        public int IDCgPhCdPh { get; set; }
        public string CdPN_root_out { get; set; }
        public string CgPN_root_out { get; set; }
        public string CdPN_root_in { get; set; }
        public string CdPN_ext_out { get; set; }
        public string CgPN_ext_out { get; set; }
        public string CgPN_root_in { get; set; }
        public string CdPN_ext_in { get; set; }
        public string CgPN_ext_in { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC> ATC { get; set; }
    }
}
