//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNtelrcom
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganInfo
    {
        public int IdInfoorgan { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string CheckBank { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string IndexO { get; set; }
        public string Checkorgan { get; set; }
        public string NameBank { get; set; }
        public string Bik { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
