//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNtelrcom
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhonesOrganizations
    {
        public int IDPhoneOrganozation { get; set; }
        public Nullable<int> IDOrganixation { get; set; }
        public Nullable<int> IDRate { get; set; }
        public string Phone { get; set; }
    
        public virtual Organizations Organizations { get; set; }
        public virtual Rate Rate { get; set; }
    }
}
